// Static fallback product data for deployment
export const staticProducts = [
  // Women's Lawn Collection - Pakistani Fashion
  {
    id: 'w1',
    _id: 'w1',
    name: 'Elegant Floral Lawn Suit',
    title: 'Elegant Floral Lawn Suit',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 5499,
    originalPrice: 7999,
    rating: 4.8,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=500',
    images: ['https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=500'],
    description: 'Beautiful floral printed lawn suit with embroidered neckline. Perfect for summer wear with premium quality fabric.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w2',
    _id: 'w2',
    name: 'Premium Embroidered Lawn',
    title: 'Premium Embroidered Lawn',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 6999,
    originalPrice: 9500,
    rating: 4.9,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500'],
    description: 'Exquisite embroidered lawn collection with intricate designs. Features premium lawn fabric with detailed embroidery work.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w3',
    _id: 'w3',
    name: 'Summer Lawn Kurti',
    title: 'Summer Lawn Kurti',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 4999,
    originalPrice: 6999,
    rating: 4.6,
    reviews: 128,
    image: 'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=500',
    images: ['https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=500'],
    description: 'Comfortable and stylish lawn kurti perfect for casual summer days. Lightweight and breathable fabric.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w4',
    _id: 'w4',
    name: 'Designer Lawn Collection',
    title: 'Designer Lawn Collection',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 8999,
    originalPrice: 12000,
    rating: 5.0,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500'],
    description: 'Premium designer lawn suit with exclusive prints and embellishments. Limited edition collection.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w5',
    _id: 'w5',
    name: 'Printed Lawn Dress',
    title: 'Printed Lawn Dress',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 5799,
    originalPrice: 8500,
    rating: 4.7,
    reviews: 167,
    image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=500',
    images: ['https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=500'],
    description: 'Vibrant printed lawn dress with modern cuts. Perfect blend of traditional and contemporary style.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w6',
    _id: 'w6',
    name: 'Luxury Lawn Ensemble',
    title: 'Luxury Lawn Ensemble',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 9999,
    originalPrice: 14000,
    rating: 4.9,
    reviews: 234,
    image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500',
    images: ['https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500'],
    description: 'Luxurious lawn ensemble with premium embroidery and fine detailing. Complete 3-piece suit.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w7',
    _id: 'w7',
    name: 'Casual Lawn Outfit',
    title: 'Casual Lawn Outfit',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 4599,
    originalPrice: 6500,
    rating: 4.5,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=500',
    images: ['https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=500'],
    description: 'Easy-to-wear casual lawn outfit for everyday comfort. Soft and breathable fabric.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'w8',
    _id: 'w8',
    name: 'Festive Lawn Collection',
    title: 'Festive Lawn Collection',
    topCategory: 'Women',
    category: 'Lawn',
    subCategory: 'Lawn',
    price: 7499,
    originalPrice: 10500,
    rating: 4.8,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=500',
    images: ['https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=500'],
    description: 'Festive lawn collection with rich colors and elegant embroidery. Perfect for special occasions.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },

  // Men's Collection - Shalwar Kameez & Kurta
  {
    id: 'm1',
    _id: 'm1',
    name: 'Premium Kurta Shalwar',
    title: 'Premium Kurta Shalwar',
    topCategory: 'Men',
    category: 'Kurta',
    subCategory: 'Shalwar Kameez',
    price: 5999,
    originalPrice: 8500,
    rating: 4.7,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=500',
    images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=500'],
    description: 'Classic kurta shalwar in premium fabric. Perfect for formal and casual occasions with elegant embroidery.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'm2',
    _id: 'm2',
    name: 'Designer Kameez Shalwar',
    title: 'Designer Kameez Shalwar',
    topCategory: 'Men',
    category: 'Kurta',
    subCategory: 'Shalwar Kameez',
    price: 7499,
    originalPrice: 10000,
    rating: 4.9,
    reviews: 234,
    image: 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=500',
    images: ['https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=500'],
    description: 'Designer kameez shalwar with intricate embroidery work. Ideal for weddings and festive occasions.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'm3',
    _id: 'm3',
    name: 'Casual Kurta Set',
    title: 'Casual Kurta Set',
    topCategory: 'Men',
    category: 'Kurta',
    subCategory: 'Casual Wear',
    price: 4999,
    originalPrice: 6999,
    rating: 4.6,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=500',
    images: ['https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=500'],
    description: 'Comfortable casual kurta set for everyday wear. Soft cotton fabric with modern cuts.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'm4',
    _id: 'm4',
    name: 'Formal Waistcoat Suit',
    title: 'Formal Waistcoat Suit',
    topCategory: 'Men',
    category: 'Formal',
    subCategory: 'Waistcoat',
    price: 8999,
    originalPrice: 12500,
    rating: 5.0,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500'],
    description: 'Elegant formal waistcoat suit with premium tailoring. Perfect for business and formal events.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'm5',
    _id: 'm5',
    name: 'Traditional Sherwani',
    title: 'Traditional Sherwani',
    topCategory: 'Men',
    category: 'Formal',
    subCategory: 'Sherwani',
    price: 9999,
    originalPrice: 15000,
    rating: 4.8,
    reviews: 167,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500',
    images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500'],
    description: 'Luxurious traditional sherwani with rich embroidery. Ideal for weddings and special ceremonies.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'm6',
    _id: 'm6',
    name: 'Cotton Kurta Pajama',
    title: 'Cotton Kurta Pajama',
    topCategory: 'Men',
    category: 'Kurta',
    subCategory: 'Casual Wear',
    price: 4599,
    originalPrice: 6500,
    rating: 4.5,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500'],
    description: 'Breathable cotton kurta pajama for summer comfort. Lightweight and easy to wear.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },

  // Kids Collection
  {
    id: 'k1',
    _id: 'k1',
    name: 'Boys Kurta Shalwar Set',
    title: 'Boys Kurta Shalwar Set',
    topCategory: 'Kids',
    category: 'Boys',
    subCategory: 'Traditional Wear',
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=500',
    images: ['https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=500'],
    description: 'Adorable kurta shalwar set for boys. Perfect for Eid and festive occasions.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'k2',
    _id: 'k2',
    name: 'Girls Fancy Frock',
    title: 'Girls Fancy Frock',
    topCategory: 'Kids',
    category: 'Girls',
    subCategory: 'Frocks',
    price: 3999,
    originalPrice: 5999,
    rating: 4.8,
    reviews: 178,
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=500'],
    description: 'Beautiful fancy frock for girls with embroidery and embellishments. Perfect for parties.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'k3',
    _id: 'k3',
    name: 'Kids Casual T-Shirt Set',
    title: 'Kids Casual T-Shirt Set',
    topCategory: 'Kids',
    category: 'Boys',
    subCategory: 'Casual Wear',
    price: 2499,
    originalPrice: 3999,
    rating: 4.6,
    reviews: 234,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500',
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500'],
    description: 'Comfortable casual t-shirt and shorts set for kids. Perfect for everyday play.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'k4',
    _id: 'k4',
    name: 'Girls Coord Set',
    title: 'Girls Coord Set',
    topCategory: 'Kids',
    category: 'Girls',
    subCategory: 'Coord Sets',
    price: 3299,
    originalPrice: 4999,
    rating: 4.7,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500',
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500'],
    description: 'Trendy coord set for girls with matching top and bottom. Stylish and comfortable.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'k5',
    _id: 'k5',
    name: 'Boys Denim Jacket',
    title: 'Boys Denim Jacket',
    topCategory: 'Kids',
    category: 'Boys',
    subCategory: 'Jackets',
    price: 4499,
    originalPrice: 6500,
    rating: 4.8,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=500',
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=500'],
    description: 'Stylish denim jacket for boys. Perfect for winter and casual outings.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'k6',
    _id: 'k6',
    name: 'Girls Summer Dress',
    title: 'Girls Summer Dress',
    topCategory: 'Kids',
    category: 'Girls',
    subCategory: 'Dresses',
    price: 2999,
    originalPrice: 4500,
    rating: 4.6,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?w=500',
    images: ['https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?w=500'],
    description: 'Light and breezy summer dress for girls. Colorful prints and comfortable fabric.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },

  // Footwear Collection
  {
    id: 'f1',
    _id: 'f1',
    name: 'Men Formal Shoes',
    title: 'Men Formal Shoes',
    topCategory: 'Footwear',
    category: 'Men',
    subCategory: 'Formal Shoes',
    price: 5999,
    originalPrice: 8500,
    rating: 4.7,
    reviews: 267,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500'],
    description: 'Premium leather formal shoes for men. Perfect for office and formal events.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f2',
    _id: 'f2',
    name: 'Men Casual Sneakers',
    title: 'Men Casual Sneakers',
    topCategory: 'Footwear',
    category: 'Men',
    subCategory: 'Sneakers',
    price: 4999,
    originalPrice: 7500,
    rating: 4.8,
    reviews: 345,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    description: 'Comfortable casual sneakers for everyday wear. Stylish design with cushioned sole.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f3',
    _id: 'f3',
    name: 'Women Heels',
    title: 'Women Heels',
    topCategory: 'Footwear',
    category: 'Women',
    subCategory: 'Heels',
    price: 4599,
    originalPrice: 6999,
    rating: 4.6,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500'],
    description: 'Elegant heels for women. Perfect for parties and formal occasions.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f4',
    _id: 'f4',
    name: 'Women Sandals',
    title: 'Women Sandals',
    topCategory: 'Footwear',
    category: 'Women',
    subCategory: 'Sandals',
    price: 3499,
    originalPrice: 5500,
    rating: 4.7,
    reviews: 289,
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500'],
    description: 'Comfortable sandals for women. Perfect for casual and summer wear.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f5',
    _id: 'f5',
    name: 'Men Peshawari Chappal',
    title: 'Men Peshawari Chappal',
    topCategory: 'Footwear',
    category: 'Men',
    subCategory: 'Chappals',
    price: 2999,
    originalPrice: 4500,
    rating: 4.9,
    reviews: 412,
    image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=500',
    images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=500'],
    description: 'Traditional Peshawari chappal handcrafted with premium leather. Comfortable and durable.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f6',
    _id: 'f6',
    name: 'Kids Sports Shoes',
    title: 'Kids Sports Shoes',
    topCategory: 'Footwear',
    category: 'Kids',
    subCategory: 'Sports Shoes',
    price: 3999,
    originalPrice: 5999,
    rating: 4.8,
    reviews: 234,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=500',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=500'],
    description: 'Comfortable sports shoes for kids. Perfect for school and outdoor activities.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f7',
    _id: 'f7',
    name: 'Women Pumps',
    title: 'Women Pumps',
    topCategory: 'Footwear',
    category: 'Women',
    subCategory: 'Pumps',
    price: 4999,
    originalPrice: 7500,
    rating: 4.7,
    reviews: 178,
    image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=500',
    images: ['https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=500'],
    description: 'Stylish pumps for women. Perfect for office and formal wear.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
  {
    id: 'f8',
    _id: 'f8',
    name: 'Men Slippers',
    title: 'Men Slippers',
    topCategory: 'Footwear',
    category: 'Men',
    subCategory: 'Slippers',
    price: 1999,
    originalPrice: 3500,
    rating: 4.5,
    reviews: 456,
    image: 'https://images.unsplash.com/photo-1582897085656-c636d006a246?w=500',
    images: ['https://images.unsplash.com/photo-1582897085656-c636d006a246?w=500'],
    description: 'Comfortable slippers for men. Perfect for home and casual wear.',
    inStock: true,
    isApproved: true,
    vendor: { name: 'StyleHub Store' }
  },
];
